# combos.py

FUNCTION_COMBOS = {
    'FUNCTION_UNDO': ('LEFT_CTRL', 'Z'),
    'FUNCTION_CUT': ('LEFT_CTRL', 'X'),
    'FUNCTION_COPY': ('LEFT_CTRL', 'C'),
    'FUNCTION_PASTE': ('LEFT_CTRL', 'V'),
    'FUNCTION_ENTER': ('LEFT_SHIFT', 'ENTER'),
    'FUNCTION_ZOOM_OUT': ('LEFT_CTRL', 'MINUS'),
    'FUNCTION_ZOOM_IN': ('LEFT_CTRL', 'EQUAL'),
}

SPECIAL_COMBOS = {
    'SPECIAL_CAPSLOCK': ('CHANGE_TO_LAYER_01', 'CAPSLOCK'),
    'SPECIAL_GRAVE': ('REPEAT', '3', 'GRAVE'),
}

PRINT_COMBOS = {
    'PRINT_LEFT_ARROW': ('LEFT_SHIFT', 'COMMA', 'EQUAL'),
    'PRINT_RIGHT_ARROW': ('EQUAL', 'LEFT_SHIFT', 'PERIOD'),
}

SHORTCUT_COMBOS = {
    'SHORTCUT_SWITCH_WINDOW_TO_LEFT': ('LEFT_GUI', 'LEFT_CTRL', 'LEFT'),
    'SHORTCUT_SWITCH_WINDOW_TO_RIGHT': ('LEFT_GUI', 'LEFT_CTRL', 'RIGHT'),
    'SHORTCUT_SWITCH_WINDOW_TO_DOWN': ('LEFT_CTRL', 'TAB'),
    'SHORTCUT_SWITCH_WINDOW_TO_UP': ('LEFT_CTRL', 'LEFT_SHIFT', 'TAB'),
}

modifierNames = {
    'LEFT_SHIFT','RIGHT_SHIFT','LEFT_CTRL','RIGHT_CTRL',
    'LEFT_ALT','RIGHT_ALT','LEFT_GUI','RIGHT_GUI'
}

